/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParkingGarageUICardLayout.java
 *
 * Created on Nov 11, 2011, 9:39:19 PM
 */
package cs414.a5.client;

import javax.swing.SwingWorker;

/**
 *
 * @author jeckstein
 */
public class ParkingGarageUICardLayout extends javax.swing.JFrame implements EventObserver {

    private String gateId = "1";
    private EventAggregator eventAggregator;    
    ViewLocator viewLocator = new ViewLocator();       
    private String currentView;
    private boolean isAdminLoggedIn=false;
    private final String CUSTOMER_VIEW = "Customer";
    private final String ADMIN_LOGIN_VIEW = "AdminLogin";
    private final String ADMIN_VIEW = "Admin";
    private String buttonText;
    
    /** Creates new form ParkingGarageUICardLayout */
    public ParkingGarageUICardLayout() {
        initComponents();        
        initFooter();  
        eventAggregator = EventAggreagtorImpl.getInstance();
        eventAggregator.subscribe(AdminLoggedInEvent.class, this);
        switchView(CUSTOMER_VIEW);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlHeader = new javax.swing.JPanel();
        jLblGateId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        btnSwitchView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblGateId.setText(getGateId());

        jLabel2.setText("Welcome to the Parking Garage.  You are at gate ");

        javax.swing.GroupLayout jPnlHeaderLayout = new javax.swing.GroupLayout(jPnlHeader);
        jPnlHeader.setLayout(jPnlHeaderLayout);
        jPnlHeaderLayout.setHorizontalGroup(
            jPnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblGateId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlHeaderLayout.setVerticalGroup(
            jPnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLblGateId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMain.setLayout(new java.awt.CardLayout());

        pnlFooter.setName("pnlFooter"); // NOI18N
        pnlFooter.setLayout(new java.awt.GridLayout(1, 0));

        btnSwitchView.setText(getButtonText());
        btnSwitchView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                        .addComponent(btnSwitchView, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSwitchView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSwitchViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchViewActionPerformed
        
        if(currentView.equals(CUSTOMER_VIEW)){
            if(!isAdminLoggedIn){
                switchView(ADMIN_LOGIN_VIEW);
            }else{
                switchView(ADMIN_VIEW);
            }
        }else{
            switchView(CUSTOMER_VIEW);
        }
        
    }//GEN-LAST:event_btnSwitchViewActionPerformed

    
    private void switchView(String viewName){
        viewLocator.showView(pnlMain, viewName);
        currentView = viewName;
        if(viewName.equals(CUSTOMER_VIEW)){
            btnSwitchView.setText("Switch to Admin View");            
        }else{
            btnSwitchView.setText("Switch to Customer View");            
        }
        validate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingGarageUICardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingGarageUICardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingGarageUICardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingGarageUICardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                
            public void run() {
                new ParkingGarageUICardLayout().setVisible(true);
            }
        });
    }
    
     /**
     * @return the gateId
     */
    public String getGateId() {
        return gateId;
    }

    /**
     * @param gateId the gateId to set
     */
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }
    
          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSwitchView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblGateId;
    private javax.swing.JPanel jPnlHeader;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables

    
    private void initFooter() {        
        this.pnlFooter.add("footer",new ViewStatusMessage());
        pnlFooter.validate();
    }

    @Override
    public <T> void notifyOnEvent(T eventPayload) {
        if(eventPayload.getClass() == AdminLoggedInEvent.class){
            handleAdminLoggedIn();            
        }
    }
    
    private void handleAdminLoggedIn(){
        isAdminLoggedIn = true;
        switchView(ADMIN_VIEW);
    }

    /**
     * @return the buttonText
     */
    public String getButtonText() {
        return buttonText;
    }

    /**
     * @param buttonText the buttonText to set
     */
    public void setButtonText(String buttonText) {
        this.buttonText = buttonText;
        firePropertyChange("buttonText", null, null);
    }
}
