/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * viewEnter.java
 *
 * Created on Nov 12, 2011, 10:17:14 AM
 */
package cs414.a5.client;

import cs414.a5.common.EntryEvent;
import cs414.a5.common.ParkingGarageException;
import java.util.Date;

/**
 *
 * @author jeckstein
 */
public class ViewEnter extends AbstractView {
    
    private Printer printer = new PrinterFakeImpl();
    
    public ViewEnter(){
        super();
        initComponents();         
    }
    /** Creates new form viewEnter */
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetTicket = new javax.swing.JButton();
        btnOpenGate = new javax.swing.JButton();
        btnCloseGate = new javax.swing.JButton();

        btnGetTicket.setText("Get Ticket");
        btnGetTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTicketActionPerformed(evt);
            }
        });

        btnOpenGate.setText("Open Gate");
        btnOpenGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenGateActionPerformed(evt);
            }
        });

        btnCloseGate.setText("Close Gate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseGate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenGate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnGetTicket)
                .addGap(18, 18, 18)
                .addComponent(btnOpenGate)
                .addGap(18, 18, 18)
                .addComponent(btnCloseGate)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTicketActionPerformed
         try {
            Date entryDate = new Date();
            EntryEvent entry = getServiceClient().createEntryEvent(entryDate, getGateId());
            printer.printEntryTicket(entry);
            btnOpenGate.setEnabled(true);
            btnGetTicket.setEnabled(false);            
            String statusMessage = "<html>The ticket has been printed. <br/> Your ticket number is: " + entry.getTicketId() + ". <br/> Please get ticket from printer. <br/> Please press Open Gate.</html>"; 
            eventAggregator.publish(new StatusEvent(statusMessage));
            //setEnterStatus("<html>The ticket has been printed. <br/> Your ticket number is: " + entry.getTicketId() + ". <br/> Please get ticket from printer. <br/> Please press Open Gate.</html>");      
        } catch (Exception ex) {
            HandleException(ex);
        } 
        
    }//GEN-LAST:event_btnGetTicketActionPerformed

    private void btnOpenGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenGateActionPerformed
        
        //setEnterStatus("Gate opening...");
        eventAggregator.publish(new StatusEvent("Gate opening..."));
        try {
            getServiceClient().openGate(getGateId());
            eventAggregator.publish(new StatusEvent("Gate opened, please select close gate after you have entered. Park safely."));                        
        } catch (Exception ex) {
            HandleException(ex);
        } 
    }//GEN-LAST:event_btnOpenGateActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseGate;
    private javax.swing.JButton btnGetTicket;
    private javax.swing.JButton btnOpenGate;
    // End of variables declaration//GEN-END:variables
}
