/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewStatusMessage.java
 *
 * Created on Nov 12, 2011, 11:45:47 AM
 */
package cs414.a5.client;

import java.util.Calendar;
import java.util.Date;
import javax.swing.SwingWorker;

/**
 *
 * @author jeckstein
 */
public class ViewStatusMessage extends AbstractView {

      private String message; 
      private static final int MESSAGE_CHECK_INTERVAL_MILLI=500;
      private static final int MESSAGE_KEEP_DURATION_SECS=3;
      
      private Date messageLastSet = new Date(); 
      
    
    /** Creates new form ViewStatusMessage */
    public ViewStatusMessage() {
        super();
        initComponents();  
        initStaleMessageCheck();
        eventAggregator.subscribe(StatusEvent.class, this);
        eventAggregator.subscribe(ExceptionOccuredEvent.class, this);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblMessage = new javax.swing.JLabel();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${message}"), lblMessage, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void notifyOnEvent(T payload) {
        if(payload.getClass() == StatusEvent.class){            
            this.setMessage(((StatusEvent)payload).getMessage());
        }
        
        if(payload.getClass() == ExceptionOccuredEvent.class){
            this.setMessage(((ExceptionOccuredEvent)payload).getException().getMessage());
        }
        
        
    }

    /**
     * @return the message
     */
    public String getMessage() {
        return message;
    }

    /**
     * @param message the message to set
     */
    public void setMessage(String message) {
        this.message = message;
        messageLastSet = new Date();
        firePropertyChange("message", null, null);
                
    }

    private void initStaleMessageCheck() {
        SwingWorker sw = new SwingWorker() {
                @Override
                protected Void doInBackground() throws Exception {
                    while(true){
                        Thread.currentThread().sleep(MESSAGE_CHECK_INTERVAL_MILLI);
                        Date now = new Date();
                        long seconds = (now.getTime()/1000) - (messageLastSet.getTime()/1000);
                       
                        if(seconds > MESSAGE_KEEP_DURATION_SECS && !message.equals(""))
                            setMessage("");                                        
                    }
                }

                
            };
            sw.execute();
    }

    
    
    
}
