/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewAdminRates.java
 *
 * Created on Nov 13, 2011, 10:06:52 AM
 */
package cs414.a5.client;

import cs414.a5.common.Rate;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 *
 * @author jeckstein
 */
public class ViewAdminRates extends AbstractView {

    private String regularRate;
    private String flatRate;
    
    
    /** Creates new form ViewAdminRates */
    public ViewAdminRates() {
        initComponents();
        initRates();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRegularRate = new javax.swing.JTextField();
        txtFlatRate = new javax.swing.JTextField();
        btnSetRate = new javax.swing.JButton();

        jLabel1.setText("Rates:");

        jLabel2.setText("Hourly:");

        jLabel3.setText("Lost / Damaged:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${regularRate}"), txtRegularRate, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${flatRate}"), txtFlatRate, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnSetRate.setText("Set Rate");
        btnSetRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFlatRate)
                            .addComponent(txtRegularRate, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(btnSetRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegularRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFlatRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnSetRate)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRateActionPerformed
        
        try{
            if(validateForm()){
                getServiceClient().setRate(new BigDecimal(getFlatRate()), true);
                getServiceClient().setRate(new BigDecimal(getRegularRate()), false);
                eventAggregator.publish(new StatusEvent("Rates updated."));
            }else{
                eventAggregator.publish(new StatusEvent("Rate values must be greater then 0."));
            }
        }catch(Exception ex){
            handleException(ex);
        }        
    }//GEN-LAST:event_btnSetRateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFlatRate;
    private javax.swing.JTextField txtRegularRate;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the regularRate
     */
    public String getRegularRate() {
        return  regularRate;
    }

    /**
     * @param regularRate the regularRate to set
     */
    public void setRegularRate(String regularRate) {
        this.regularRate = regularRate;
        firePropertyChange("regularRate", null, null);
    }

    /**
     * @return the flatRate
     */
    public String getFlatRate() {
        return flatRate;
    }

    /**
     * @param flatRate the flatRate to set
     */
    public void setFlatRate(String flatRate) {
        this.flatRate = flatRate;
        firePropertyChange("flatRate", null, null);
    }

    private void initRates() {
        try{
            Rate[] rates = getServiceClient().getCurrentRates();
            for(Rate rate : rates){
                if(rate.getIsFlatRate()){
                    setFlatRate(rate.getRate().toString());
                }else{
                    setRegularRate(rate.getRate().toString());
                }
            }
        }catch(Exception ex){
            handleException(ex);
        }
    }

    private boolean validateForm() {
        try{
            BigDecimal rRate = new BigDecimal(getRegularRate());
            BigDecimal fRate = new BigDecimal(getFlatRate());
        
                       
            if(rRate.compareTo(BigDecimal.ZERO) <= 0)
                return false;

            if(fRate.compareTo(BigDecimal.ZERO) <= 0)
                return false;

            return true;
            
        }catch(Exception ex){
            return false;
        }
    }
}
