/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewAdmin.java
 *
 * Created on Nov 13, 2011, 9:46:44 AM
 */
package cs414.a5.client;

/**
 *
 * @author jeckstein
 */
public class ViewAdmin extends AbstractView {

    ViewLocator viewLocator = new ViewLocator();            
    
    /** Creates new form ViewAdmin */
    public ViewAdmin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminMain = new javax.swing.JPanel();
        btnSetRates = new javax.swing.JButton();
        btnUsageReport = new javax.swing.JButton();

        pnlAdminMain.setLayout(new java.awt.CardLayout());

        btnSetRates.setText("Set Rates");
        btnSetRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRatesActionPerformed(evt);
            }
        });

        btnUsageReport.setText("View Usage Report");
        btnUsageReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsageReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminMain, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnSetRates, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsageReport, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetRates)
                    .addComponent(btnUsageReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAdminMain, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRatesActionPerformed
        viewLocator.showView(pnlAdminMain, "AdminRates");
    }//GEN-LAST:event_btnSetRatesActionPerformed

    private void btnUsageReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsageReportActionPerformed
        // TODO add your handling code here:
        viewLocator.showView(pnlAdminMain, "AdminUsageReport");
    }//GEN-LAST:event_btnUsageReportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetRates;
    private javax.swing.JButton btnUsageReport;
    private javax.swing.JPanel pnlAdminMain;
    // End of variables declaration//GEN-END:variables
}
