/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewEntry.java
 *
 * Created on Nov 12, 2011, 2:51:32 PM
 */
package cs414.a5.client;

import cs414.a5.common.EntryEvent;
import java.util.Date;
import javax.swing.SwingWorker;

/**
 *
 * @author jeckstein
 */
public class ViewEntry extends AbstractEntryExitView {

    private Printer printer = new FakePrinterAdapter();
    private EntryEvent currentEntry;
    
    
    /** Creates new form ViewEntry */
    public ViewEntry() {
        initComponents();
        pnlRates.add(new ViewRateSchedule());        
        pnlRates.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetTicket = new javax.swing.JButton();
        btnOpenGate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pnlRates = new javax.swing.JPanel();
        btnEnterGarage = new javax.swing.JButton();

        btnGetTicket.setText("Get Entry Ticket");
        btnGetTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTicketActionPerformed(evt);
            }
        });

        btnOpenGate.setText("Open Gate");
        btnOpenGate.setEnabled(false);
        btnOpenGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenGateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pnlRates.setLayout(new java.awt.GridLayout(1, 0));

        btnEnterGarage.setText("Enter Garage");
        btnEnterGarage.setEnabled(false);
        btnEnterGarage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterGarageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenGate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterGarage, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(pnlRates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRates, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGetTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenGate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnterGarage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTicketActionPerformed
        try {
            Date entryDate = new Date();
            currentEntry = getServiceClient().createEntryEvent(entryDate, getGateId());
            printer.printEntryTicket(currentEntry);
            btnOpenGate.setEnabled(true);
            btnGetTicket.setEnabled(false);            
            String statusMessage = "The ticket has been printed. Your ticket number is: " + currentEntry.getTicketId() + ". Please press Open Gate."; 
            eventAggregator.publish(new StatusEvent(statusMessage));
            //setEnterStatus("<html>The ticket has been printed. <br/> Your ticket number is: " + entry.getTicketId() + ". <br/> Please get ticket from printer. <br/> Please press Open Gate.</html>");      
        } catch (Exception ex) {
            handleException(ex);
        } 
    }//GEN-LAST:event_btnGetTicketActionPerformed

    private void btnOpenGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenGateActionPerformed
                
        eventAggregator.publish(new StatusEvent("Gate opening..."));
        try {
            getServiceClient().openGate(getGateId());
            eventAggregator.publish(new StatusEvent("Gate opened, please select 'Enter Garage' to enter or 'Cancel' to leave."));                        
            btnOpenGate.setEnabled(false);
            btnEnterGarage.setEnabled(true);
            btnCancel.setEnabled(true);
        } catch (Exception ex) {
            handleException(ex);
        } 
    }//GEN-LAST:event_btnOpenGateActionPerformed

    
    
    private void btnEnterGarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterGarageActionPerformed
        
        eventAggregator.publish(new StatusEvent("Thank you.  Gate will close shortly. Park safely."));
        doCloseGate();
    }//GEN-LAST:event_btnEnterGarageActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        try {
            getServiceClient().cancelEntry(currentEntry.getTicketId());
            eventAggregator.publish(new StatusEvent("Ticket cancelled.  Gate will close shortly. Goodbye."));                                               
            doCloseGate();
        } catch (Exception ex) {
            handleException(ex);
        } 
    }//GEN-LAST:event_btnCancelActionPerformed

    private void doCloseGate(){        
       btnCancel.setEnabled(false);
       btnEnterGarage.setEnabled(false);
       closeGate();
    }            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEnterGarage;
    private javax.swing.JButton btnGetTicket;
    private javax.swing.JButton btnOpenGate;
    private javax.swing.JPanel pnlRates;
    // End of variables declaration//GEN-END:variables

    


}
