/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewEntry.java
 *
 * Created on Nov 12, 2011, 2:51:32 PM
 */
package cs414.a5.client;

import cs414.a5.common.EntryEvent;
import java.util.Date;

/**
 *
 * @author jeckstein
 */
public class ViewEntry extends AbstractView {

    private Printer printer = new PrinterFakeImpl();
    
    /** Creates new form ViewEntry */
    public ViewEntry() {
        initComponents();
        pnlRates.add(new ViewRateSchedule());        
        pnlRates.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetTicket = new javax.swing.JButton();
        btnOpenGate = new javax.swing.JButton();
        btnCloseGate = new javax.swing.JButton();
        pnlRates = new javax.swing.JPanel();

        btnGetTicket.setText("Get Entry Ticket");
        btnGetTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTicketActionPerformed(evt);
            }
        });

        btnOpenGate.setText("Open Gate");
        btnOpenGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenGateActionPerformed(evt);
            }
        });

        btnCloseGate.setText("Close Gate");

        pnlRates.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseGate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenGate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(pnlRates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRates, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGetTicket)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpenGate)
                        .addGap(18, 18, 18)
                        .addComponent(btnCloseGate)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTicketActionPerformed
        try {
            Date entryDate = new Date();
            EntryEvent entry = getServiceClient().createEntryEvent(entryDate, getGateId());
            printer.printEntryTicket(entry);
            btnOpenGate.setEnabled(true);
            btnGetTicket.setEnabled(false);            
            String statusMessage = "<html>The ticket has been printed. <br/> Your ticket number is: " + entry.getTicketId() + ". <br/> Please get ticket from printer. <br/> Please press Open Gate.</html>"; 
            eventAggregator.publish(new StatusEvent(statusMessage));
            //setEnterStatus("<html>The ticket has been printed. <br/> Your ticket number is: " + entry.getTicketId() + ". <br/> Please get ticket from printer. <br/> Please press Open Gate.</html>");      
        } catch (Exception ex) {
            HandleException(ex);
        } 
    }//GEN-LAST:event_btnGetTicketActionPerformed

    private void btnOpenGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenGateActionPerformed
                
        eventAggregator.publish(new StatusEvent("Gate opening..."));
        try {
            getServiceClient().openGate(getGateId());
            eventAggregator.publish(new StatusEvent("Gate opened, please select close gate after you have entered. Park safely."));                        
        } catch (Exception ex) {
            HandleException(ex);
        } 
    }//GEN-LAST:event_btnOpenGateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseGate;
    private javax.swing.JButton btnGetTicket;
    private javax.swing.JButton btnOpenGate;
    private javax.swing.JPanel pnlRates;
    // End of variables declaration//GEN-END:variables

    


}
